### ISSUE TITLE
 already running

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#125]
Where is the problem?! I reboot the server and it is the first time I want to run workerman

```
php index.php start -d
```
The result is

>Workerman[index.php] start in DAEMON mode
Workerman[index.php] already running

**Comment by walkor** [comment]
Because you reboot the server and the pid file of workerman which stored workerman's pid remains on disk.
When workerman starting, start script will get the pid  from the file and check if the process of the pid still alive.
Maybe another process started which pid is the same as workerman's old pid.

Just delete the pid file of workerman after you reboot your server.

**Comment by sm2017** [comment]
I reopen it as you mark this issue as ```enhancement```

**Comment by walkor** [comment]
Thanks

**Comment by sm2017** [comment]
Any updates?

**Comment by dorw123** [comment]
Hi walkor. 

I have a CentOS server. I would like to know how to start my server as a deamon on startup. I put the script in rc.local to run on startup but it seems that the server is not starting. When checking with status parameter says "not run".

**Comment by ishland** [comment]
I think you need to check if that process is a workerman process.

**Comment by linkec** [comment]
@dorw123 did you use -d parameter? or set Worker::$daemonize = true; I think it should fix your problem.

**Comment by detain** [comment]
To check to see if its running and safely remove pid files can do something like:
```bash
if [ $(php start.php status 2>/dev/null|grep "PROCESS STATUS"|wc -l) -eq 0 ]; then
  # clean up old run, remove pid file or run a stop command?
  php start.php stop
  php start.php start -d
fi```
