### ISSUE TITLE
About multiple processes to share a listening socket

### ISSUE THREAD

**Issue by jiaoge008** [walkor/Workerman#156]
master进程fork出来的子进程，会对同一个socket进行监听，网络数据来了之后是如何分配给子进程worker的。会出现惊群效应么？

**Comment by walkor** [comment]
Please use english, that can help all people to understand each other. Thanks. : -)

**Comment by jiaoge008** [comment]
The master process forks multi worker process，these worker processes will listen the same socket。How to decide which worker process handle the data that come from the listened socket? Does thundering herd will happen?

**Comment by sudevva** [comment]
The free worker will get the data. This thing is behind OS load balance. Walkor can you write some article(work flow maybe) about how it works? When the worker start to listen and how they listen one socket. It's will be very interesting.

**Comment by walkor** [comment]
Under Linux (Or POSIX type OS), using fork() will cause the forked child to have copies of all the parent's file descriptors. Any that it does not close will continue to be shared.  Master process create a listening socket and fork , child process will share it and can be used to accept() new sockets for clients. This is how many servers, including Apache in most cases, work.

**Comment by walkor** [comment]
Every child process can use ```accept()``` to accept a connection on the shared listening socket,
but only one process will success and other processes will fail(```accept()``` return false), that cause [thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem) problem.

**Comment by jiaoge008** [comment]
It means that the OS(POSIX type OS) is in charge of dispatching data. Is it?

**Comment by walkor** [comment]
Workerman will use socket option [SO_REUSEPORT](https://lwn.net/Articles/542629/)  when ```$worker->reusePort``` is set to be ```true``` (this feature only support in php7 or greater). ```SO_REUSEPORT``` is a new feature for Linux kernel 3.9.

When the SO_REUSEPORT option is not enabled, a single listening socket notifies workers about incoming connections, and each worker tries to take a connection.
![image](https://cloud.githubusercontent.com/assets/6073368/24320774/ec85f77a-1176-11e7-931b-936d54d5a803.png)

With the SO_REUSEPORT option enabled, there are multiple socket listeners for each IP address and port combination, one for each worker process. The kernel determines which available socket listener (and by implication, which worker) gets the connection. This can reduce lock contention between workers accepting new connections, and improve performance on multicore systems. However, it can also mean that when a worker is stalled by a blocking operation, the block affects not only connections that the worker has already accepted, but also connection requests that the kernel has assigned to the worker since it became blocked.
![image](https://cloud.githubusercontent.com/assets/6073368/24320778/01e68314-1177-11e7-9559-567a2daaafe4.png)

**Comment by jiaoge008** [comment]
Thank you very much.

**Comment by jiaoge008** [comment]
Thank you very much.

**Comment by sudevva** [comment]
+1 thank you
