### ISSUE TITLE
master branch AsyncTcpConnection bug

### ISSUE THREAD

**Issue by gouchaoer** [walkor/Workerman#173]
in `https://github.com/walkor/tcp-proxy-demo`, if you replace the the Workerman direcotry with master branch then async tcp can not established.

I don't have a linux xdebug environment so I can't debug what is wrong.

**Comment by walkor** [comment]
It is not workerman's bug.
The workerman in https://github.com/walkor/tcp-proxy-demo is too old.
AsyncTcpConnection must call ```connect``` method to establish connection now.

I have fixed in https://github.com/walkor/tcp-proxy-demo/commit/611872455eedcec5d4c06d9c0c6745e6ffa12e95#diff-09912625b277e8728d35f29c441c74c3 just now.
