### ISSUE TITLE
Problem on windows

### ISSUE THREAD

**Issue by mininzidane** [walkor/Workerman#272]
On windows 10 there is no process in netstat after starting worker. When comment line workerman/workerman/Worker.php:534 (initWorkers() disabled when OS is not Linux), the problem is solved. Investigate it.

**Comment by walkor** [comment]
It works fine for me. 
Can you show your codes?

```initWorkers``` should not be called in the windows system, and we do not want the master process listen port because windows can not use ```fork()``` method to create multi processes.  The mechanism here is different from the Linux system.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
If this problem persists and we can reopen this.

**Comment by cobreen** [comment]
Hello. I'm using OpenServer on windows 10
My configuration is:
PHP 7.4

When i run "php worker.php start -d"
It continues to echo into a console.
How can i stop it?
Also, it ignores all commands, so "php worker.php" is enough.
I want to launch server remotely, but workerman locks whole system

**Comment by walkor** [comment]
Because php not support `pcntl` and `posix` extensions under Windows system, so workerman does not support any commands for windows and all output will echo into console.
In addition, workerman does not support setting the number of processes (`$worker->count`) under Windows system that means the process count is 1 for every worker.

If you want to make full use of the features of worker man, it is recommended to use Linux system.

**Comment by cobreen** [comment]
Thank you!
