### ISSUE TITLE
Heartbeat in WebSocket

### ISSUE THREAD

**Issue by plashenkov** [walkor/Workerman#324]
Hi!

How to implement a heartbeat for WebSocket server? I can see, that here: https://github.com/walkor/Workerman/blob/master/Protocols/Ws.php there are some ping timers, etc. But this is a client if I understand correctly.

How can we turn on pings, etc. for the server?

**Comment by walkor** [comment]
Yes Ws.php is client side protocol.
If client send ping then workerman(as websocket server) will send pong automatically.  
So you do not do anything.

**Comment by plashenkov** [comment]
Thank you!

Yes, I know that it answers to pings. But how to implement sending pings to clients for the server? And checking for pongs.

**Comment by walkor** [comment]
You can use Timer to send pings to client like this.
```
use Workerman\Lib\Timer;
$worker = new Worker('websocket://0.0.0.0:8080');
$worker->onWorkerStart = function($worker) {
    $time_interval = 10;
    Timer::add($time_interval, function()use($worker)) {
        foreach($worker->connections as $connection) {
            $connection->send(pack('H*', '898000000000'), true)
        }
    }
};
```

**Comment by nexen2** [comment]
Walkor, its clear to use a timer. But what about data?

Your code is not working, Chrome is disconnecting on ping, writing an error to log:

socket.js?v=1550695204:185 WebSocket connection to 'ws://crm.local/websocket' failed: A server must not mask any frames that it sends to the client.

Same troubles with closing. In time Chrome just drops connection on WS socket close so its ok, but Firefox waits its closed on server side, and closes a connection from client side then. But your "close" packet seems incorrect, bcz Firefox after page refresh (F5 or any other action) writes to log:

The connection to ws://crm.local/websocket was interrupted while the page was loading.

People say that bcz connection was not clearly closed from server side.

Please, fix that and provide a functionality to control a Websocket service correct packets - both ping and close and any other if it exists.

**Comment by nexen2** [comment]
I tested Wrench library and how it make a ping.

It sends, if I had sent a "time()" as ping:

//                   1 5 5 0 7 5 3 2 9 6
//890a31353530373533323936

Where 89 an opcode, 0a - length. You have 8 zeros, so seems you did a mistake: not "898000000000", but "89080000000000" is correct - you missed a zero before last "8".

Also, it works with Chrome, but failing in Firefox. Seems Firefox does not like "zeros" string. But it accepts normal string, like timestamp for example.

**Comment by walkor** [comment]
Yes `898000000000` is wrong.
`890800000000` is correct.

`onWebSocketClose` will be called when a close frame received for websocket. onClose will be called when  a fin package received for tcp.  The order is usually `onWebSocketClose` followed by `onClose`.

**Comment by nexen2** [comment]
And hi again. :-)

It looks like server cannot close the connection. It closing up to 10-15 seconds later, on some "timeout" or similar setting.

I added a erorr_log() to TcpConnection::destroy() and discovered its called several times (3-5 usually) before connection is closed really.

Running "server.php connections" shows these unclosed connections.

Again, Both Chrome and Firefox writes error messages to console about connection problem with WS host.

So, "workerman" is doing something wrong when connection is closing. Wrench library has no such problems, but this library have no multi-thread support.

https://github.com/varspool/Wrench

P.S. BTW i tried "0x880x00" - my v64 Firefox fails, it wants at least 6-8 bytes data in a ping packet to treat it correctly. "Empty" ping packet makes browser disconnect a WS connection, not keeping it alive. That's why I sent a "time()" data.

**Comment by walkor** [comment]
Please zip all project then upload it and show how to reproduce the problem.

**Comment by zhuwei** [comment]
```
use Workerman\Lib\Timer;
$worker = new Worker('websocket://0.0.0.0:8080');
$worker->onWorkerStart = function($worker) {
    $time_interval = 10;
    Timer::add($time_interval, function()use($worker)) {
        foreach($worker->connections as $connection) {
            $connection->send(pack('H*', '890400000000'), true)
        }
    }
};
```
这个代码会导致 Error package. package_length=2298478592
