### ISSUE TITLE
Multiple workers on Windows host

### ISSUE THREAD

**Issue by gotzmann** [walkor/Workerman#540]
Unfortunately, I have to debug production services on Windows hosts. Is it possible to start workers in parallel? I've tried that doc:

http://doc.workerman.net/faq/multi-woker-for-windows.html

but that method do not work for me. When I tried to launch two different scripts with command:

```php app.php jobs.php```

then only first one app.php is really started.

**Comment by gotzmann** [comment]
I mean app.php and jobs.php are not daemonized for easy of debug.

**Comment by walkor** [comment]
It works fine for me. For example.

**app.php**
```php
<?php
use Workerman\Worker;

require_once __DIR__ . '/vendor/autoload.php';

$app = new Worker('websocket://0.0.0.0:2020');
$app->onMessage = function($connection, $data) {
	$connection->send('hello app');
};

Worker::runAll();

```
**jobs.php**
```php
<?php
use Workerman\Worker;

require_once __DIR__ . '/vendor/autoload.php';

$job = new Worker('http://0.0.0.0:2021');
$job->onMessage = function($connection, $request) {
	$connection->send('hello job');
};

Worker::runAll();
```
**start**
`php app.php jobs.php`

**output**
```
>php app.php job.php
----------------------- WORKERMAN -----------------------------
Workerman version:4.0.6          PHP version:5.6.32
------------------------ WORKERS -------------------------------
worker               listen                              processes status
none                 http://0.0.0.0:2021                 1         [ok]
none                 websocket://0.0.0.0:2020            1         [ok]
```

**notice**
PHP can't create processes under windows because `pcntl` and `POSIX` extensions don't support windows, so when workerman runs under windows, each service is single process (meaning `$worker->count` is invalid), and it can't use `stop` `reload` `status` `connections` and other commands. Linux system is recommended for production environment.
