### ISSUE TITLE
What the best way to use workerman with yii2?

### ISSUE THREAD

**Issue by shizzic** [walkor/workerman#948]
Just share your implemination please. I think it may be a big help for many ppl.

**Comment by joanhey** [comment]
I have an implementation with [Adapterman](https://github.com/joanhey/AdapterMan).

![image](https://github.com/walkor/workerman/assets/249085/bf122293-dd06-4e43-9e1f-d40429356fda)

I can help you and show the code.

PD: I think that I read somewhere, than exist an implementation only for yii2.

**Comment by shizzic** [comment]
> I have an implementation with [Adapterman](https://github.com/joanhey/AdapterMan).
> 
> ![image](https://user-images.githubusercontent.com/249085/256856115-bf122293-dd06-4e43-9e1f-d40429356fda.png)
> 
> I can help you and show the code.
> 
> PD: I think that I read somewhere, than exist an implementation only for yii2.

Please, share your code)

**Comment by joanhey** [comment]
The code in the benchmark:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/yii2

The important parts:
**server.php**
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/yii2/server.php

Added the 2 lines:
```php
 $_SERVER['SCRIPT_FILENAME'] = '/app/index.php';
 $_SERVER['SCRIPT_NAME'] = '/index.php';
```
As yii2, don't created it correctly.

The WorkerTimer is because the bench need to have a `Date:` header.
And I didn't want to touch the initial yii2 app code.

**index.php** 
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/yii2/app/index.php#L54-L62
![image](https://github.com/walkor/workerman/assets/249085/3c052e19-8583-42ef-ba4e-9728eae25762)

To run with Workerman, you only need to comment the line 54.

Dockefile
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/yii2/yii2-workerman.dockerfile
![image](https://github.com/walkor/workerman/assets/249085/6053cd68-2754-4f2e-b9c6-148dbb9cf79b)

Here I need to change 1 line in yii2, or stop there always (marked with the arrow)
And run it  `php server.php start`.

Remember that Adapterman is only an application server, you need to serve static files with the webserver.

**Comment by shizzic** [comment]
Thank you!
